# Generated by Django 5.2.5 on 2025-09-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_classroom_remove_projectcontributor_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main_app.classroom'),
        ),
    ]
