# Generated by Django 5.2.5 on 2025-09-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(),
        ),
    ]
