# Generated by Django 5.2.5 on 2025-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assistance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='win',
            field=models.TextField(null=True),
        ),
    ]
