# Generated by Django 5.2.5 on 2025-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_submission_assistance_submission_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='project_covers/'),
        ),
    ]
