# Generated by Django 5.2.5 on 2025-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_submission_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://res.cloudinary.com/dvhwvkip4/image/upload/v1757074823/0x0_indooc.png'),
        ),
    ]
